### ISSUE TITLE
Joining a nonexistent room causes crash

### ISSUE THREAD

**Issue by acramernc** [Curtisww17/VoteNote-iOS#11]
if a user enters an invalid code there is a crash in dbConnection.swift in joinRoom() line 227 
![image](https://user-images.githubusercontent.com/30380231/110973985-fad49400-832b-11eb-878d-85250ecf4496.png)
![image](https://user-images.githubusercontent.com/30380231/110974227-4edf7880-832c-11eb-9588-ebce529d651d.png)
![image](https://user-images.githubusercontent.com/30380231/110974105-25265180-832c-11eb-8f1a-ee7d0413156d.png)

**Comment by Curtisww17** [comment]
Fixed in commit 5303e90c55a823894c3b87b5302d4f25e309555f
