### ISSUE TITLE
Extraneous DB calls after leaving a room

### ISSUE THREAD

**Issue by acramernc** [Curtisww17/VoteNote-iOS#25]
after leaving a room, getQueue and getHistory are called again after about 15 seconds. 

This can be replicated by the following steps:
Host a room
switch to the queue page
leave the room
wait

**Comment by acramernc** [comment]
It also calls getUsers()

**Comment by acramernc** [comment]
#26 keeps this from crashing, however it still continues to grab those after leaving the room

![image](https://user-images.githubusercontent.com/30380231/112219417-52f87980-8bfb-11eb-8846-4f1b14f89bdd.png)

**Comment by PJKnightR** [comment]
Issue should be fixed in newest commit
