### ISSUE TITLE
Queue no longer updates automatically when first adding songs

### ISSUE THREAD

**Issue by PJKnightR** [Curtisww17/VoteNote-iOS#27]
After you add a song, the queue does not seem to update a large portion of the time until you go to the room page.

**Comment by Curtisww17** [comment]
why's this assigned to me? I don't think updating the queue is my task

**Comment by PJKnightR** [comment]
I don't believe that we have a task for it assigned to anyone. However, this began after the update queue method was moved around and the Queue class was changed, so I assigned it to you as I thought you were the one who made that change and could potentially know why its happening.

**Comment by PJKnightR** [comment]
I reopened this as the refresh does not consistently work when first adding songs. I have specifically ran into this issue when adding liked songs to the queue, so Im wondering if the queue is not being refreshed correctly outside of when you just add songs from search

**Comment by Curtisww17** [comment]
unassigned myself s you're describing issues that I had nothing to do with
