### ISSUE TITLE
Crash when Adding music to the queue.

### ISSUE THREAD

**Issue by PJKnightR** [Curtisww17/VoteNote-iOS#32]
I received this crash after adding songs from the recommended music page to the queue. This crash does not seem to be consistent, but I believe I have had it before. It's occurring in the Spotify class so Im not sure who did this function.
<img width="892" alt="Screen Shot 2021-03-27 at 7 17 12 PM" src="https://user-images.githubusercontent.com/20178264/112737451-15fcf180-8f31-11eb-9fb0-fbb2ae4a0109.png">

**Comment by PJKnightR** [comment]
Update: After more testing I have gotten this crash to occur several times when adding recommended songs.

**Comment by Curtisww17** [comment]
unassigned myself- I know nothing about the recommended songs

**Comment by PJKnightR** [comment]
Haven't seen this happening anymore so its probably good
