### ISSUE TITLE
Songs seem to be randomly removed from the queue

### ISSUE THREAD

**Issue by PJKnightR** [Curtisww17/VoteNote-iOS#33]
After sitting on the Queue page for about a minute, I found that songs in the queue were randomly being removed over time after I paused the song currently playing. I think this may have something to do with how we add songs to the queue after the prior song is almost done, however I am not sure. I was playing the really short Pink Floyd song and watched as the songs were removed, and wonder if the timer for adding the next song continues when paused, so it just adds the next song once it thinks the current is over. I assigned this to anyone who has worked on the player and queue more recently.

**Comment by Curtisww17** [comment]
@gabearmpa Probably a bug with your "autoplay", are you taking into account when a user pauses?

**Comment by PJKnightR** [comment]
Seems that the veto song button was somehow being activated when the user button was pushed. This should now be fixed.
