### ISSUE TITLE
Crash on Skipping?

### ISSUE THREAD

**Issue by acramernc** [Curtisww17/VoteNote-iOS#37]
![image](https://user-images.githubusercontent.com/30380231/113884763-42183e00-978d-11eb-9cb1-f99453948d80.png)
This bug occurred on the QueueUpdate branch

Steps taken before crash:
Hosted a room
Added the top 4 songs returned by searching revival (Revival, fortunate Son, Revival's in the Air, and Have you Ever Seen the Rain)
Skipped 2 songs
On skipping the third song, spotify began playing the third song and the skipped song was moved into history
following this, the app crashed

**Comment by acramernc** [comment]
Seems to only happen when you login with spotify and the app doesnt automatically pause the music

**Comment by Curtisww17** [comment]
repeat of #32 , closing
