### ISSUE TITLE
Song Votes not removed from list when song is removed from Queue

### ISSUE THREAD

**Issue by PJKnightR** [Curtisww17/VoteNote-iOS#43]
When a song is removed for the queue in some form (Dequeue, Veto), the users votes for it remain in the DB, thus causing the app to think they have already been upvoted or downvoted.

**Comment by acramernc** [comment]
made a deleteVote method to be used by @PJKnightR  to fix this

**Comment by PJKnightR** [comment]
This was fixed in my latest commit.
