### ISSUE TITLE
DB Voting method does not properly function

### ISSUE THREAD

**Issue by PJKnightR** [Curtisww17/VoteNote-iOS#8]
Does not connect to the database correctly, fails to find the db document.

**Comment by acramernc** [comment]
Fixing tags and adding reference error image
![image](https://user-images.githubusercontent.com/30380231/110972691-44bc7a80-832a-11eb-8ec5-c2eb890006d1.png)

**Comment by acramernc** [comment]
the db end of this now works as of #12 , however, the votes are not being displayed on the UI

**Comment by acramernc** [comment]
fixed by @PJKnightR
